apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-example
spec:
  selector:
    matchLabels:
      app: quarkus-example
  template:
    metadata:
      labels:
        app: quarkus-example
        deployment: quarkus-example
    spec:
      containers:
      - name: quarkus-example
        image: image-registry.openshift-image-registry.svc.cluster.local:5000/cicd-pipelines/springapp@sha256:633ee888dc49401717c732da505747b00cf0e312dac34c2cf454a042a17c0e40
