apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-example
  namespace: quarkus-app
spec:
  selector:
    matchLabels:
      app: quarkus-example
  template:
    metadata:
      labels:
        app: quarkus-example
        deployment: quarkus-example
    spec:
      containers:
      - name: quarkus-example
        image: quay.io/rh_ee_tavelino/ci-quarkus@sha256:d448e87b2c87f14668d88a54063427f9fcfaf1613ec0ef9b065da86b60d304df