apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-example
  namespace: quarkus-app
spec:
  selector:
    matchLabels:
      app: quarkus-example
  template:
    metadata:
      labels:
        app: quarkus-example
        deployment: quarkus-example
    spec:
      containers:
      - name: quarkus-example
        image: quay.io/rh_ee_tavelino/ci-quarkus@sha256:d159417d4bda08c272b55fd8145c501c543ffe54faafebd33cb1db2f066c0a71