apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-settings-pvc
  namespace: openshift-pipelines
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
