apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-kustomize-repo
  annotations:
    tekton.dev/displayName: "Update Kustomize Git Repository"
  namespace: cicd-pipelines
spec:
  params:
    - name: gitRepositoryUrl
      type: string
    - name: gitRepositoryRevision
      type: string
      default: argocd
    - name: gitPath
      type: string
      default: k8s/deployment.yaml
    - name: imageTag
      type: string
    - name: imageName
      type: string
    - name: verbose
      type: string
      default: "true"
  workspaces:
    - name: repository
  steps:
    - name: git-checkout
      image: alpine/git:v2.45.1
      workingDir: /workspace/repository
      env:
        - name: HOME
          value: /tekton/home
        - name: GIT_USER_NAME
          valueFrom:
            secretKeyRef:
              name: git-credentials
              key: username
        - name: GIT_EMAIL
          valueFrom:
            secretKeyRef:
              name: git-credentials
              key: email
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: git-credentials
              key: password
      script: |
        #!/usr/bin/env sh
        mkdir -p "$HOME"
        git config --global user.name "$GIT_USER_NAME"
        git config --global user.email "$GIT_EMAIL"
        git config --global credential.helper store
        git config --global --add safe.directory /workspace/repository
        echo "https://$GIT_USER_NAME:$GIT_PASSWORD@github.com" > ~/.git-credentials

        if [ "$(params.verbose)" = "true" ] ; then
          set -x
          echo "**** Cloning $(params.gitRepositoryUrl) into $(pwd)"
        fi

        git clone "$(params.gitRepositoryUrl)" .
        git checkout "$(params.gitRepositoryRevision)"
        git pull origin "$(params.gitRepositoryRevision)"
    - name: update-yaml
      image: alpine/git:v2.45.1
      workingDir: /workspace/repository
      script: |
        #!/usr/bin/env sh
        set -e
        echo "**** Working directory: $(pwd)"
        if [ "$(params.verbose)" = "true" ] ; then
          echo "**** Updating $(params.gitPath) image tag to $(params.imageTag)"
        fi
        sed -i 's|image:.*|image: $(params.imageName)@\$(params.imageTag)|' $(params.gitPath)
        cat $(params.gitPath)
    - name: commit-push-changes
      image: alpine/git:v2.45.1
      workingDir: /workspace/repository
      env:
        - name: HOME
          value: /tekton/home
        - name: GIT_USER_NAME
          valueFrom:
            secretKeyRef:
              name: git-credentials
              key: username
        - name: GIT_EMAIL
          valueFrom:
            secretKeyRef:
              name: git-credentials
              key: email
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: git-credentials
              key: password
      script: |
        #!/usr/bin/env sh
        mkdir -p "$HOME"
        git config --global user.name "$GIT_USER_NAME"
        git config --global user.email "$GIT_EMAIL"
        git config --global credential.helper store
        echo "https://$GIT_USER_NAME:$GIT_PASSWORD@github.com" > ~/.git-credentials
        git add .
        git commit --allow-empty -m "[OpenShift Pipeline] Updating $(params.gitPath) image tag to $(params.imageTag)"
        git push origin "$(params.gitRepositoryRevision)" -v
