apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
 name: ci-quarkus-pipeline-binding
spec:
 params:
 - name: gitrevision
   value: $(body.pull_request.head.sha)
 - name: gitrepositoryurl
   value: $(body.repository.html_url)