apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
 name: ci-quarkus-pipeline-binding
spec:
 params:
 - name: APP_NAME
   value: $(body.repository.name)
 - name: REPO_FULL_NAME
   value: $(body.repository.name)
 - name: GIT_REVISION
   value: $(body.ref)
 - name: GIT_REPO
   value: $(body.repository.html_url)
