apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pipeline-template
spec:
  params:
    - description: Nome da aplicação
      name: APP_NAME
    - description: URL do repositório Git da aplicação (usado para clone)
      name: GIT_REPO
    - description: Branch ou tag para checkout da aplicação
      name: GIT_REVISION
    - description: Nome do repo para pull request
      name: REPO_FULL_NAME
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: java-pipeline-run-
      namespace: prodepa-pipelines
    spec:
      pipelineRef:
        name: java-pipeline
      podTemplate:
        securityContext:
          fsGroup: 0
          runAsUser: 0
      serviceAccountName: pipeline
      params:
        - name: APP_NAME
          value: $(tt.params.APP_NAME)
        - name: GIT_REPO
          value: $(tt.params.GIT_REPO)
        - name: GIT_REPO_PLATAFORM
          value: "https://github.com/TiagoAvelino/Manifests"
        - name: GIT_REVISION
          value: $(tt.params.GIT_REVISION)
        - name: GIT_REVISION_DESTINATION
          value: "hml"
        - name: IMAGE_NAME
          value: "quay.io/rh_ee_tavelino/"
        - name: REPO_FULL_NAME
          value: $(tt.params.REPO_FULL_NAME)
      workspaces:
        - name: workspace
          persistentVolumeClaim:
            claimName: workspace-pvc
        - name: dockerconfig
          secret:
            secretName: my-quay-secret
        - name: maven_settings
          persistentVolumeClaim:
            claimName: maven-settings-pvc
