apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: java-pipeline
  namespace: openshift-pipelines
spec:
  params:
    - description: Nome da aplicação
      name: APP_NAME
      type: string
    - description: URL do repositório Git da aplicação
      name: GIT_REPO
      type: string
    - default: main
      description: Branch ou tag para checkout da aplicação
      name: GIT_REVISION
      type: string
    - description: Nome da imagem para construir e empurrar
      name: IMAGE_NAME
      type: string
    - default: .
      name: CONTEXT
      type: string
    - description: URL do repositório Git dos manifests
      name: GIT_REPO_PLATAFORM
      type: string
      default: "https://github.com/TiagoAvelino/Manifests"
  tasks:
    - name: fetch-repository
      params:
        - name: URL
          value: $(params.GIT_REPO)
        - name: REVISION
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: output
          workspace: workspace
    - name: build-jar
      runAfter:
        - fetch-repository
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: maven
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      params:
        - name: GOALS
          value:
            - clean
            - package
        - name: CONTEXT_DIR
          value: .
      workspaces:
        - name: source
          workspace: workspace
        - name: maven_settings
          workspace: maven_settings
    - name: buildah
      runAfter:
        - build-jar
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: CONTEXT
          value: $(params.CONTEXT)
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: buildah-com
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: source
          workspace: workspace
        - name: dockerconfig
          workspace: dockerconfig
    - name: update-kustomize
      runAfter:
        - buildah
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: update-kustomize-repo
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      params:
        - name: gitRepositoryUrl
          value: $(params.GIT_REPO_PLATAFORM)
        - name: gitRepositoryRevision
          value: "main"
        - name: gitPath
          value: overlays/dev/deployment.yaml
        - name: imageTag
          value: $(tasks.buildah.results.IMAGE_DIGEST)
        - name: imageName
          value: $(tasks.buildah.results.IMAGE_URL)
      workspaces:
        - name: repository
          workspace:  workspace
  workspaces:
    - description: Workspace para persistir dados entre as tarefas
      name: workspace
    - description: Workspace contendo o config.json para autenticação no Quay.io
      name: dockerconfig
    - description: Workspace para configurações Maven, pode estar vazio
      name: maven_settings