apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: java-pipeline-run-teste
  namespace: prodepa-pipelines
spec:
  pipelineRef:
    name: java-pipeline
  podTemplate:
    securityContext:
      runAsUser: 0
  serviceAccountName: pipeline
  params:
    - name: APP_NAME
      value: "QuarkusApp"
    - name: GIT_REPO
      value: "https://github.com/TiagoAvelino/Quarkus-Example"
    - name: GIT_REPO_PLATAFORM
      value: "https://github.com/TiagoAvelino/Manifests"
    - name: GIT_REVISION
      value: "dev"
    - name: GIT_REVISION_DESTINATION
      value: "hml"
    - name: IMAGE_NAME
      value: "image-registry.openshift-image-registry.svc.cluster.local:5000/prodepa-pipelines/"
    - name: REPO_FULL_NAME
      value: TiagoAvelino/Quarkus-Example
  workspaces:
    - name: workspace
      persistentVolumeClaim:
        claimName: workspace-pvc
    - name: maven_settings
      configMap:
        name: my-maven-settings
    - name: empty
      emptyDir: {}