apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: java-pipeline
  namespace: openshift-pipelines
spec:
  params:
    - description: Nome da aplicação
      name: APP_NAME
      type: string
    - description: URL do repositório Git da aplicação (usado para clone)
      name: GIT_REPO
      type: string
    - description: Branch ou tag para checkout da aplicação
      name: GIT_REVISION
      type: string
      default: dev
    - description: Branch ou tag para checkout da aplicação
      name: GIT_REVISION_DESTINATION
      type: string
      default: hml
    - description: Nome da imagem para construir e empurrar
      name: IMAGE_NAME
      type: string
    - description: URL do repositório Git dos manifests
      name: GIT_REPO_PLATAFORM
      type: string
      default: "https://github.com/TiagoAvelino/Manifests"
    - description: Nome do repo para pull request
      name: REPO_FULL_NAME
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: URL
          value: $(params.GIT_REPO)
        - name: REVISION
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
      workspaces:
        - name: output
          workspace: workspace
    - name: build-jar
      runAfter:
        - fetch-repository
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: maven
          - name: namespace
            value: openshift-pipelines
      params:
        - name: GOALS
          value:
            - clean
            - package
      workspaces:
        - name: source
          workspace: workspace
        - name: maven_settings
          workspace: maven_settings
    - name: convert-app-name
      runAfter:
        - build-jar
      taskRef:
        name: lowercase-app-name
      params:
        - name: APP_NAME
          value: $(params.APP_NAME)
    - name: buildah
      runAfter:
        - convert-app-name
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: buildah-1-18-0
          - name: namespace
            value: openshift-pipelines
      params:
        - name: IMAGE
          # Use the lower-case APP_NAME from the conversion task.
          value:  $(params.IMAGE_NAME)$(tasks.convert-app-name.results.lowerAppName):latest
      workspaces:
        - name: source
          workspace: workspace
        - name: dockerconfig
          workspace: dockerconfig
    - name: update-kustomize
      runAfter:
        - buildah
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: update-kustomize-repo
          - name: namespace
            value: openshift-pipelines
      params:
        - name: gitRepositoryUrl
          value: $(params.GIT_REPO_PLATAFORM)
        - name: gitRepositoryRevision
          value: "main"
        - name: gitPath
          value: overlays/dev/deployment.yaml
        - name: imageTag
          value: $(tasks.buildah.results.IMAGE_DIGEST)
        - name: imageName
          value: $(tasks.buildah.results.IMAGE_URL)
      workspaces:
        - name: repository
          workspace: workspace
    - name: create-pr
      runAfter:
        - update-kustomize
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: github-open-pr
          - name: namespace
            value: openshift-pipelines
      params:
        - name: REPO_FULL_NAME
          value: $(params.REPO_FULL_NAME)
        - name: HEAD
          value: $(params.GIT_REVISION)
        - name: BASE
          value: $(params.GIT_REVISION_DESTINATION)
        - name: TITLE
          value: "Merge changes from dev to hml"
        - name: BODY
          value: "Automated pull request created by OpenShift Pipeline"
        - name: GITHUB_TOKEN_SECRET_NAME
          value: git-credentials
        - name: GITHUB_TOKEN_SECRET_KEY
          value: password
  workspaces:
    - description: Workspace para persistir dados entre as tarefas
      name: workspace
    - description: Workspace contendo o config.json para autenticação no Quay.io
      name: dockerconfig
    - description: Workspace para configurações Maven, pode estar vazio
      name: maven_settings
