apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-example
  namespace: openshift-gitops
spec:
  destination:
    namespace: quarkus-app
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: overlays/dev/
    repoURL: 'https://github.com/TiagoAvelino/Manifests'
    targetRevision: main
  syncPolicy:
    automated: {}