apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-quarkus
spec:
  destination:
    namespace: ''
    server: https://kubernetes.default.svc
  source:
    path: overlays/dev
    repoURL: https://github.com/TiagoAvelino/Manifests
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
