apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: maven-21
  namespace: openshift-pipelines
spec:
  description: "Custom Maven task that builds with Java 21"
  params:
    - name: GOALS
      type: array
      description: The Maven goals to run
      default:
        - package
    - name: MAVEN_MIRROR_URL
      type: string
      description: The Maven repository mirror url
      default: ""
    - name: SUBDIRECTORY
      type: string
      description: The subdirectory for sources
      default: .
  stepTemplate:
    computeResources: {}
    env:
      - name: PARAMS_MAVEN_MIRROR_URL
        value: $(params.MAVEN_MIRROR_URL)
      - name: PARAMS_SUBDIRECTORY
        value: $(params.SUBDIRECTORY)
      - name: WORKSPACES_SOURCE_PATH
        value: $(workspaces.source.path)
      - name: WORKSPACES_SOURCE_BOUND
        value: $(workspaces.source.bound)
      - name: WORKSPACES_SERVER_SECRET_PATH
        value: $(workspaces.server_secret.path)
      - name: WORKSPACES_SERVER_SECRET_BOUND
        value: $(workspaces.server_secret.bound)
      - name: WORKSPACES_PROXY_SECRET_PATH
        value: $(workspaces.proxy_secret.path)
      - name: WORKSPACES_PROXY_SECRET_BOUND
        value: $(workspaces.proxy_secret.bound)
      - name: WORKSPACES_PROXY_CONFIGMAP_PATH
        value: $(workspaces.proxy_configmap.path)
      - name: WORKSPACES_PROXY_CONFIGMAP_BOUND
        value: $(workspaces.proxy_configmap.bound)
      - name: WORKSPACES_MAVEN_SETTINGS_PATH
        value: $(workspaces.maven_settings.path)
      - name: WORKSPACES_MAVEN_SETTINGS_BOUND
        value: $(workspaces.maven_settings.bound)
  steps:
    # 1) keep the "maven-generate" step the same (UBI minimal, script logic, etc.)
    - name: maven-generate
      image: 'registry.redhat.io/ubi9/ubi-minimal@sha256:bafd57451de2daa71ed301b277d49bd120b474ed438367f087eac0b885a668dc'
      script: |
        # identical to your original maven-1-18-0 script logic...
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      volumeMounts:
        - mountPath: /scripts
          name: scripts-dir
        - mountPath: /maven-generate
          name: maven-settings-dir

    # 2) change the "maven-goals" step to the Java 21 image
    - name: maven-goals
      image: 'registry.access.redhat.com/ubi8/openjdk-21:1.20'    # <--- KEY CHANGE
      command:
        - /usr/bin/mvn
      args:
        - '-s'
        - maven-generate/settings.xml
        - '$(params.GOALS[*])'
      workingDir: $(workspaces.source.path)/$(params.SUBDIRECTORY)
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      volumeMounts:
        - mountPath: /maven-generate
          name: maven-settings-dir
  volumes:
    - name: scripts-dir
      emptyDir: {}
    - name: maven-settings-dir
      emptyDir: {}
  workspaces:
    - name: source
      description: The workspace with your Maven project
    - name: maven_settings
      description: The workspace with custom maven settings (optional)
      optional: true
    - name: server_secret
      optional: true
    - name: proxy_secret
      optional: true
    - name: proxy_configmap
      optional: true
