apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: java-pipeline
  namespace: openshift-pipelines
spec:
  params:
    - description: Nome da aplicação
      name: APP_NAME
      type: string
    - description: URL do repositório Git
      name: GIT_REPO
      type: string
    - default: main
      description: Branch ou tag para checkout
      name: GIT_REVISION
      type: string
    - description: Nome da imagem para construir e empurrar
      name: IMAGE_NAME
      type: string
    - default: .
      name: CONTEXT
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: URL
          value: $(params.GIT_REPO)
        - name: REVISION
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: output
          workspace: workspace
    - name: build-jar
      runAfter:
        - fetch-repository
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: maven
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      params:
        - name: GOALS
          value: 
            - clean
            - package
        - name: CONTEXT_DIR
          value: .
      workspaces:
        - name: source
          workspace: workspace
        - name: maven_settings
          workspace: maven_settings 
    - name: build-and-push-image
      runAfter:
        - build-jar
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: CONTEXT
          value: $(params.CONTEXT)
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: source
          workspace: workspace
        - name: dockerconfig
          workspace: dockerconfig
  workspaces:
    - description: Workspace para persistir dados entre as tarefas
      name: workspace
    - description: Workspace contendo o config.json para autenticação no Quay.io
      name: dockerconfig
    - description: Workspace para configurações Maven, pode estar vazio
      name: maven_settings