apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-interceptors-role
rules:
- apiGroups: ["triggers.tekton.dev"]
  resources:
    - eventlisteners
    - clustertriggerbindings
    - clusterinterceptors
    - triggerbindings
    - triggertemplates
    - triggers
    - interceptors
  verbs: ["get", "list", "watch"]
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns"]
  verbs: ["create", "get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "secrets", "events"]
  verbs: ["get", "list", "watch", "create", "patch"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["impersonate"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-interceptors-binding
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: openshift-pipelines
roleRef:
  kind: ClusterRole
  name: cluster-interceptors-role
  apiGroup: rbac.authorization.k8s.io
