apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: openshift-pipelines
  annotations:
    tekton.dev/git-0: 'https://github.com/TiagoAvelino/Quarkus-Example'
data:
  password: 
  username: VGlhZ29BdmVsaW5v
type: kubernetes.io/basic-auth
