apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-example
  labels:
    app: quarkus-example
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  selector:
    matchLabels:
      app: quarkus-example
  template:
    metadata:
      labels:
        app: quarkus-example
    spec:
      containers:
        - name: quarkus-example
          image: quay.io/rh_ee_tavelino/ci-quarkus:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
      # imagePullSecrets:
      #   - name: my-quay-secret
