apiVersion: v1
kind: ConfigMap
metadata:
  name: my-maven-settings
  namespace: prodepa-pipelines
data:
  settings.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                  https://maven.apache.org/xsd/settings-1.0.0.xsd">

      <!-- 1. Credentials for pushing to releases & snapshots -->
      <servers>
        <server>
          <id>maven-releases</id>
          <username>admin</username>
          <password>123456</password>
        </server>
        <server>
          <id>maven-snapshots</id>
          <username>admin</username>
          <password>123456</password>
        </server>
      </servers>

      <!-- 2. Mirror EVERY request through your Nexus public group -->
      <mirrors>
        <mirror>
          <id>nexus-public</id>
          <mirrorOf>*</mirrorOf>
          <url>http://nexus-nexus.apps.tiago-cluster.sandbox1712.opentlc.com/repository/maven-public/</url>
        </mirror>
      </mirrors>

      <!-- 3. A “profile” to explicitly declare your Nexus repos as real repos,
           and allow HTTP access (activeByDefault) -->
      <profiles>
        <profile>
          <id>nexus-repos</id>
          <activation>
            <activeByDefault>true</activeByDefault>
          </activation>

          <repositories>
            <repository>
              <id>maven-releases</id>
              <url>http://nexus-nexus.apps.tiago-cluster.sandbox1712.opentlc.com/repository/maven-releases/</url>
              <releases>
                <enabled>true</enabled>
              </releases>
              <snapshots>
                <enabled>false</enabled>
              </snapshots>
            </repository>
            <repository>
              <id>maven-snapshots</id>
              <url>http://nexus-nexus.apps.tiago-cluster.sandbox1712.opentlc.com/repository/maven-snapshots/</url>
              <releases>
                <enabled>false</enabled>
              </releases>
              <snapshots>
                <enabled>true</enabled>
              </snapshots>
            </repository>
          </repositories>

          <pluginRepositories>
            <pluginRepository>
              <id>maven-releases</id>
              <url>http://nexus-nexus.apps.tiago-cluster.sandbox1712.opentlc.com/repository/maven-releases/</url>
              <releases>
                <enabled>true</enabled>
              </releases>
              <snapshots>
                <enabled>false</enabled>
              </snapshots>
            </pluginRepository>
            <pluginRepository>
              <id>maven-snapshots</id>
              <url>http://nexus-nexus.apps.tiago-cluster.sandbox1712.opentlc.com/repository/maven-snapshots/</url>
              <releases>
                <enabled>false</enabled>
              </releases>
              <snapshots>
                <enabled>true</enabled>
              </snapshots>
            </pluginRepository>
          </pluginRepositories>

        </profile>
      </profiles>

      <!-- 4. (Optional) Activate your new profile explicitly -->
      <activeProfiles>
        <activeProfile>nexus-repos</activeProfile>
      </activeProfiles>

    </settings>
