kind: Secret
apiVersion: v1
metadata:
  name: my-quay-secret
  namespace: openshift-pipelines
data:
  config.json: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJjbWhmWldWZmRHRjJaV3hwYm04NlZFWlJRV05hYVhWQ1dUQlRkVEZWWjBabmJrTm5XR04zZG01VGNUTmxVMUJNTDNWQmFXTjNkbG93ZEdGQ2NFaEVNelZxWTJjek1qbE1MMWwwUmtGbGFBPT0iLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
type: Opaque
